### PR TITLE
Add package.json

### LINKED ISSUE #10: create npm package
I would like to use this package to speed up my nodejs backend.
Can you create an npm package please?

If you need help creating a package.json, consult the [leftpad](https://github.com/tmcw/leftpad/blob/master/package.json) repo please.

### PR DESCRIPTION
**Pull request by strugee**
Fixes #10

### CODE REVIEW

**Comment by strugee** [comment]
:P

**Comment by leonadler** [comment]
conemu_2016-06-22_11-02-40
:cry:

**Comment by strugee** [comment]
Ah yeah, I didn't publish it because I figured @cbrandolino would (to get npm publishing rights)

**Comment by cbrandolino** [comment]
omg that's too sweet! gonna do it now, even tho lately ive been focusing on the basic arithmetics angular directive

**Comment by cbrandolino** [comment]
https://www.npmjs.com/package/jquery-basic-arithmetic-plugin @leonadler life makes sense again all of a sudden. thanks again @strugee !

**Comment by leonadler** [comment]
Thank you, I will refactor my backend to use your plugin for performance!

**Comment by cbrandolino** [comment]
ok wtf 
screenshot 2016-06-25 01 10 10

**Comment by strugee** [comment]
@cbrandolino my pleasure :D

**Pull request merged**
